services:
  nginx:
    image: nginx:1.31.6-alpine3.24-slim
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./php/src:/var/www/html:ro
    depends_on:
      - php
    networks:
      - process_network

  php:
    build:
      context: ./php
    volumes:
      - ./php/src:/var/www/html
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - process_network

  db:
    image: mariadb:13.0.2-ubi10
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--protocol=TCP" ]
      # 以下は適宜調整
      # 起動するまでの30sは1s間隔で確認する
      start_period: 30s
      start_interval: 1s
      # 起動後は30s間隔で最大5回リトライする
      interval: 30s
      timeout: 1s
      retries: 5
    networks:
      - process_network

volumes:
  db_data:

networks:
  process_network:
    driver: bridge
